# DB Configuration
spring.datasource.master.hikari:
  pool-name: master
  maximum-pool-size: 10
  minimum-idle: 3
  username: jwlee
  password: Epsltm1124!
  driver-class-name: com.mysql.cj.jdbc.Driver
  connection-timeout: 10000
  idle-timeout: 60000
  jdbc-url: jdbc:mysql://daworld.synology.me:3307/oukitchen?autoReconnect=true&useSSL=true&useUnicode=true&characterEncoding=UTF-8


# 마이바티스 설정
mybatis:
  type-handlers-package: com.project.toy.common.utils.mybatis
  configuration:
    map-underscore-to-camel-case: true

kakao.api.url: https://dapi.kakao.com/v2/local/search/keyword.json
kakao.api.key: bc204b28eae40a69fbcbef0bc0db3c61
